[Application]
Name = Store Management System
Version = 1.0.0
Website = https://example.com
MainWindow = http://127.0.0.1:8000

[PHP]
Version = 7.4
Port = 8000
DocumentRoot = public
StartupUrl = /

[Database]
Driver = SQLite
Path = database/storemanagement.sqlite
